title: MCOMP0001
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Arquivos: https://github.com/wmpjrufg/MCOMP001/tree/main/files

color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Importante
    color: blue
  new:
    title: Novo
    color: green
  note:
    title: Nota
    color: purple
  warning:
    title: Aviso
    color: red
  
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Back to top link
back_to_top: true
back_to_top_text: "Voltar ao início"

footer_content: "Copyright &copy; 2023. Construído por Wanderlei Malaquias Pereira Junior e seu grupo de pesquisa.</a>"
